# Generated by Django 3.2.8 on 2021-12-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leacots',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(auto_created=True, help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='名称', max_length=100, verbose_name='名称')),
                ('content', models.TextField(help_text='内容', verbose_name='内容')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'tb_leacots',
                'ordering': ['-update_time', '-id'],
            },
        ),
    ]
