# Generated by Django 3.2.8 on 2021-12-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leacots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leacots',
            name='id',
            field=models.IntegerField(auto_created=True, help_text='ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
