# Generated by Django 3.2.8 on 2021-12-06 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(auto_created=True, help_text='文章ID', primary_key=True, serialize=False, verbose_name='文章ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('title', models.CharField(help_text='文章标题', max_length=150, verbose_name='文章标题')),
                ('content', mdeditor.fields.MDTextField(help_text='文章标题', verbose_name='文章内容')),
                ('abstract', models.TextField(default=None, help_text='文章标签', verbose_name='摘要')),
                ('click', models.IntegerField(default=0, help_text='点击量', verbose_name='点击量')),
                ('like_num', models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数')),
                ('author_name', models.CharField(default='兔子', help_text='作者名字', max_length=10, verbose_name='作者名字')),
                ('source', models.TextField(default='', help_text='网址', max_length=400, verbose_name='网址')),
                ('update_time', models.DateTimeField(default=datetime.datetime(2021, 12, 6, 15, 20, 23, 905930), help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'tb_article',
                'ordering': ['-update_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuthorAndTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_time', models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 12, 6, 15, 20, 23, 906409), help_text='创建时间', verbose_name='时间')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'verbose_name': '书和标签',
                'verbose_name_plural': '书和标签',
                'db_table': 'tb_tab_article',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.IntegerField(auto_created=True, help_text='标签ID', primary_key=True, serialize=False, verbose_name='标签ID')),
                ('tag_name', models.CharField(help_text='输入标签', max_length=64, verbose_name='标签')),
                ('a_id', models.ManyToManyField(through='blog.AuthorAndTag', to='blog.Article')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tb_tag',
            },
        ),
        migrations.AddField(
            model_name='authorandtag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tag'),
        ),
    ]
