# Generated by Django 3.2.8 on 2021-12-14 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='', help_text='文章内容', verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 12, 21, 0, 781120), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='authorandtag',
            name='push_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 12, 14, 12, 21, 0, 781787), help_text='创建时间', verbose_name='时间'),
        ),
    ]
