# Generated by Django 3.2.8 on 2021-12-06 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_delete',
            field=models.BooleanField(default=0, help_text='软删除', verbose_name='软删除'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 17, 38, 54, 761358), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='authorandtag',
            name='push_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 12, 6, 17, 38, 54, 761832), help_text='创建时间', verbose_name='时间'),
        ),
    ]
