# Generated by Django 3.2.8 on 2021-12-06 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211206_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorandtag',
            name='is_delete',
            field=models.BooleanField(default=0, help_text='软删除', verbose_name='软删除'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 17, 40, 1, 625619), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='authorandtag',
            name='push_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 12, 6, 17, 40, 1, 626105), help_text='创建时间', verbose_name='时间'),
        ),
    ]
