# Generated by Django 3.2.8 on 2021-12-06 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211206_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 18, 42, 7, 375554), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='authorandtag',
            name='push_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 12, 6, 18, 42, 7, 376026), help_text='创建时间', verbose_name='时间'),
        ),
        migrations.AlterModelTable(
            name='authorandtag',
            table='tb_tag_article',
        ),
    ]
