# Generated by Django 3.2.8 on 2021-12-07 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211206_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_url',
            field=models.CharField(default='../../media/img/lgd.png', help_text='图片路径', max_length=100, verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 15, 24, 31, 125137), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='authorandtag',
            name='push_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 12, 7, 15, 24, 31, 125628), help_text='创建时间', verbose_name='时间'),
        ),
    ]
