# Generated by Django 3.2.8 on 2021-12-23 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesDownload', '0011_auto_20211214_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content',
            field=models.TextField(default='', help_text='内容', verbose_name='内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='resourceandtag',
            name='push_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='时间'),
        ),
    ]
