# Generated by Django 3.2.8 on 2021-12-15 10:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesDownload', '0015_auto_20211215_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 10, 56, 45, 177035), help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='resourceandtag',
            name='push_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='时间'),
        ),
    ]
