# Generated by Django 3.2.8 on 2021-12-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesDownload', '0018_alter_resource_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content',
            field=models.TextField(default='', help_text='内容', verbose_name='内容'),
            preserve_default=False,
        ),
    ]
